# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
 
variables:
  ImageName: 'anandskd/dockerdemo:$(Build.BuildId)'
 
stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
    - task: Docker@1
      displayName: 'Build the Docker image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'ananddocker'
        command: 'Build an image'
        dockerFile: '**/Dockerfile'
        imageName: '$(ImageName)'
        includeLatestTag: true
        useDefaultContext: false
        buildContext: '.'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'demoaz'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          docker build -t myadregistry.azurecr.io/newapps:latest .
          az acr login -n myadregistry
          docker push myadregistry.azurecr.io/newapps:latest
    - task: Docker@1
      displayName: 'Push the Docker image to Dockerhub'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'ananddocker'
        command: 'Push an image'
        imageName: '$(ImageName)'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    - task: AzureContainerApps@1
      inputs:
         appSourcePath: '$(Build.SourcesDirectory)/src'
         azureSubscription: 'demoaz'
         acrName: 'myadregistry'
         containerAppName: 'myadcontainerapp1810'
         resourceGroup: 'demoRG'
